# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - busybeeapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish -c Release -o ./publish --no-restore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: busybeeapi
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write # Required for Azure login with OIDC
      contents: read

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: busybeeapi
          path: ./publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0BC3C6AFC8FE4508B66F82347539D20F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9803E744396F421DA8314E6E9EADDFA2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_929C2EFA326B4A628863401C1556B810 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'busybeeapi'
          slot-name: 'Production'
          package: ./publish
