name: Build and deploy ASP.NET Core app to Azure Web App - busybeeapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore BusyBee.API/BusyBee.API.csproj

      - name: Build with dotnet
        run: dotnet build BusyBee.API/BusyBee.API.csproj --configuration Release

      - name: Publish
        run: dotnet publish BusyBee.API/BusyBee.API.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: List files in current directory
        run: ls -la

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'busybeeapi'
          slot-name: 'Production'
          package: .net-app
