name: Build and deploy ASP.NET Core app to Azure Web App - busybeeapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore BusyBee.API/BusyBee.API.csproj

      - name: Build with dotnet
        run: dotnet build BusyBee.API/BusyBee.API.csproj --configuration Release

      - name: Publish
        run: dotnet publish BusyBee.API/BusyBee.API.csproj --configuration Release --output ./publish

      # Проверяем, что файлы опубликовались
      - name: Check publish directory
        run: ls -la ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app  # Изменил имя артефакта для ясности
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: List files recursively
        run: ls -Rla

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8CB68700C8574AF1BA735D4528B60375 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_10AE413EEAF44B68A525735E5933800D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0EB79B9536384BA5A21FDE78E0F647D6 }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'busybeeapi'
          slot-name: 'Production'
          package: dotnet-app
